### PR TITLE
Updated deploy workflow for PR preview

### LINKED ISSUE #91: Feature Request : Deployment preview Workflow/GHA
We are in need of a deployment preview workflow for our Uptane repository. This workflow is intended to operate specifically for pull requests, providing our reviewers with a live link to assess and review the proposed changes on our website before finalizing the merge process. The primary objective is to have a system where pull requests can initiate a build on a dedicated path, allowing reviewers to evaluate the results of these changes.

We have a preference for open-source alternatives for deployment and do not wish to rely on third-party services like Netlify for deployment or any paid alternatives. Instead, we are actively seeking open-source alternatives that offer similar functionality, We are open to all suggestions, and if there is a way to achieve this directly through GitHub Pages by creating a custom workflow, that would be highly advantageous.

### PR DESCRIPTION
**Pull request by devilkiller-ag**
# Summary of Changes
Updated deploy workflow for PR preview.

## Related Issue
Closes #91 

## Checklist
- [x] I have read and followed the [project's contribution guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md), including code style and commit message conventions.
- [x] My code is well-documented, and I've updated relevant documentation.
- [x] I have added or updated test cases to ensure the code's functionality.
- [x] I have tested these changes on my local environment.
- [x] All tests pass, and there are no new linting errors.
- [x] I have reviewed and proofread my code and the changes.
- [x] The branch is up-to-date with the base branch.

## Reviewer(s)
@Abhijay007

### CODE REVIEW

**Comment by hexsecs** [comment]
It looks like this might be causing an error...
```
Run if [ "pull_request" == "pull_request" ]; then
yarn run v1.22.21
$ docusaurus build --basepath /pr-150
error: unknown option '--basepath'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by devilkiller-ag** [comment]
Hi @hexsecs I think no file change was pushed earlier. Now I have pushed the updated code. Can you check it now?

**Comment by devilkiller-ag** [comment]
Hi @hexsecs, It seems that pull bot is forcibly changing my PR to delete all the changes.

**Review by Abhijay007 — CHANGES_REQUESTED** [review]
Merge conflicts needs to be resolved

**Comment by devilkiller-ag** [comment]
I checked for the cause of my changes getting force deleted by a bot. It was due to an unconfigured pull bot installed from my side. I have rectified it. I will push the new changes soon.

**Pull request closed without merging**
