### PR TITLE
IEEE/ISTO changes.  Will need updates later as the JDF comes online

### PR DESCRIPTION
**Pull request by JustinCappos**

### CODE REVIEW

**Comment by JustinCappos** [comment]
Made a few more minor tweaks to remove the membership agreement.  Thanks for catching that Lois!

**Comment by JustinCappos** [comment]
@trishankatdatadog Would you kindly give a quick review?  Lois looked but we need someone external to review and merge...

**Comment by JustinCappos** [comment]
> Does it make sense to update the timeline as well?

I added something tentative now.  We likely will need to revise later.

**Comment by trishankatdatadog** [comment]
Sorry, just saw this, will get to it ASAP

**Pull request merged**
