### PR TITLE
Ag dev

### LINKED ISSUE #116: [Bug Report] - Argos CI Screenshots failing at `run yarn playwrite test` step
### Describe the bug.

Run yarn playwright test
yarn run v1.22.19
$ /home/runner/work/uptane.github.io/uptane.github.io/node_modules/.bin/playwright test

Error: ENOENT: no such file or directory, open './screenshot.css'

   at argos/screenshot.spec.js:10

   8 | const sitemapPath = './build/sitemap.xml';
   9 | const stylesheetPath = './screenshot.css';
> 10 | const stylesheet = fs.readFileSync(stylesheetPath).toString();
     |                       ^
  11 |
  12 | // Wait for hydration, requires Docusaurus v2.[4](https://github.com/uptane/uptane.github.io/actions/runs/6695724126/job/18191913819#step:7:5).3+
  13 | // Docusaurus adds a <html data-has-hydrated="true"> once hydrated

    at Object.<anonymous> (/home/runner/work/uptane.github.io/uptane.github.io/argos/screenshot.spec.js:[10](https://github.com/uptane/uptane.github.io/actions/runs/6695724126/job/18191913819#step:7:11):23)

Error: No tests found

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Describe the steps to reproduce the behavior.

Happens every time `Argos CI Screenshots` CI workflow is run.

### Expected behavior.

It should run without issue.

### Screenshots.

_No response_

### Operating environment

Ubuntu

### What browsers are you seeing the problem on?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devilkiller-ag**
# Summary of Changes

Fixed a bug in the causing `yarn playwright test` to fail due to an error in the screenshot.css path.

## Related Issue

Closes #116 

## Checklist
- [x] I have read and followed the [project's contribution guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md), including code style and commit message conventions.
- [x] My code is well-documented, and I've updated relevant documentation.
- [x] I have added or updated test cases to ensure the code's functionality.
- [x] I have tested these changes on my local environment.
- [x] All tests pass, and there are no new linting errors.
- [x] I have reviewed and proofread my code and the changes.
- [x] The branch is up-to-date with the base branch.

## Reviewer(s)
@hexsecs

### CODE REVIEW

**Comment by hexsecs** [comment]
@devilkiller-ag I think you also need to commit the yarn.lock file.

**Comment by hexsecs** [comment]
@devilkiller-ag Great success! It looks like it is working. Once you commit the updated yarn.lock I'll merge in the PR!
image

Thanks for the hard work.

**Comment by devilkiller-ag** [comment]
I am not sure why it didn't update yarn.lock. But I just removed and readded the yarn.lock file. Now it should be good to go.

**Comment by hexsecs** [comment]
I spoke too soon.

It is now running (yay!) but the compare path has an issue. It looks like it's adding an additional '/' to the base path URL.
image

**Comment by hexsecs** [comment]
@devilkiller-ag I just confirmed it's working. I'll approve and merge.

**Review by hexsecs — APPROVED** [review]

**Pull request merged**
