### PR TITLE
Add deployment considerations for 2.0.0

### PR DESCRIPTION
**Pull request by mnm678**
cc @jhdalek55

### CODE REVIEW

**Comment by jhdalek55** [comment]
I checked the PDF version and saw that we had the page numbers. There had been discussion about adding section numbers and perhaps even line numbers. Perhaps these were done on HTML version? I couldn't open that version to take a peak because of file size.

It's important to get these posted ASAP, so if the other changes would be too difficult to achieve, let's get this up there while we figure out the rest.

**Comment by mnm678** [comment]
I updated this to add the section numbers. Do we also want line numbers? I don't remember what the consensus was there.

I skipped the page numbers in the html as there isn't a clear sense of a "page" as there is with the pdf, but if there's a clear place to put them I can add it there as well

**Comment by jhdalek55** [comment]
Thanks for adding the section numbers. That along with the page numbers is what really mattered. @iramcdonald was the primary advocate for adding the line numbers. Before we reach out and ask, how difficult would it be to add the line numbers? I don't want to throw too much on your plate.  You're correct about the HTML version as there is no real "pages" in that version.

**Comment by mnm678** [comment]
Adding the line numbers can't be done directly through pandoc, so will be a bit harder, but still possible if that's something we need.

**Comment by iramcdonald** [comment]
Hi Marina and Lois,

We can live without line numbers in the Deployment Best Practices, if we do
have the section
numbers in the HTML/PDF.

In the actual Uptane Standard, the line numbers are more important for OEMs
writing contracts
for their suppliers that are precise about specific Uptane requirements.
Also for external review
comments.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Thanks @iramcdonald.Let's wait another day to see if we get any further comments and then we'll merge.

**Pull request merged**
