### PR TITLE
New Text for Contributing Page

### PR DESCRIPTION
**Pull request by jhdalek55**

### CODE REVIEW

**Comment by hexsecs** [comment]
We already have a contributing.md file at...
https://uptane.github.io/docs/learn-more/participate

I think the pull request needs to be changes to this file...
https://github.com/uptane/uptane.github.io/blob/uptane_docusaurus/docs/learn-more/participate.md

**Comment by Abhijay007** [comment]
> We already have a contributing.md file at... https://uptane.github.io/docs/learn-more/participate
> 
> I think the pull request needs to be changes to this file... https://github.com/uptane/uptane.github.io/blob/uptane_docusaurus/docs/learn-more/participate.md

@hexsecs we need a contributing file for guiding contributors to do code and non-coding (like adding blog) contributions to the repo

**Comment by jhdalek55** [comment]
Ok Then I will submit changes to that page. The existing text is not
correct.

Lois

**Comment by Abhijay007** [comment]
@jhdalek55 just update the text in this file, I will update it in the existing MD files later, just like we did for the About Us and Timeline page

**Comment by jhdalek55** [comment]
Closing this down because the text will be updated in an existing file.

**Pull request closed without merging**
