### PR TITLE
Configuration for Tailwind Integration

### PR DESCRIPTION
**Pull request by devilkiller-ag**
# Summary of Changes
This PR adds configuration for Tailwind CSS

## Related Issue
Fixes first task of #179 

## Checklist
- [x] I have read and followed the [project's contribution guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md), including code style and commit message conventions.
- [x] My code is well-documented, and I've updated relevant documentation.
- [x] I have added or updated test cases to ensure the code's functionality.
- [x] I have tested these changes on my local environment.
- [x] All tests pass, and there are no new linting errors.
- [x] I have reviewed and proofread my code and the changes.
- [x] The branch is up-to-date with the base branch.

## Reviewer(s)
@Abhijay007

### CODE REVIEW

**Review by Abhijay007 — CHANGES_REQUESTED** [review]
"Hey @devilkiller-ag, I've reviewed the code, and there are a few things that need to be considered. The Initialization of Tailwind to our Docusaurus site looks good to me, as it didn't break our site too much. However, there are some styling changes that seem to have been adopted due to Tailwind, so we need to look into that. For instance, take a look at these screenshots here.

- one the blog page 

image

Screenshot 2024-02-04 143725

- on docs pages 

Screenshot 2024-02-04 143701

Screenshot 2024-02-04 143558

This issue needs to be resolved.  Most of the custom components appear to be in good shape. To address these concerns, we may need to delve into the styles of custom CSS and adjust them accordingly using Tailwind. While you can incorporate these changes in the same file, I recommend considering a separate file for Tailwind, as demonstrated in the resources I shared earlier.

Let's ensure everything aligns smoothly with our design standards, it will help us in long run to use tailwind effectively.

**Comment by devilkiller-ag** [comment]
Sure @Abhijay007, I will look into this.

**Comment by devilkiller-ag** [comment]
Hi @Abhijay007, I have made changes to the heading styling. However, I think I will need to convert the whole custom.css into tailwind, to fix the styling. I am currently doing these changes in a different CSS file. I have changed the heading styling into tailwind in the above commit.

**Review by Abhijay007 — DISMISSED** [review]
The code changes LGTM. Now, you can work on converting one of the components and create a separate PR for that. Once that's done, we will merge both of these PRs.

**Comment by devilkiller-ag** [comment]
> The code changes LGTM. Now, you can work on converting one of the components and create a separate PR for that. Once that's done, we will merge both of these PRs.

Okay Sure!

**Comment by Abhijay007** [comment]
closing this as we already have version of it here : https://github.com/uptane/uptane.github.io/pull/185

**Pull request closed without merging**
