### PR TITLE
Ag dev

### LINKED ISSUE #99: Create CI Workflow for visual regression testing
The docusaurus site has an interesting suggestion for setting up an automated visual regression testing workflow. See here..
https://docusaurus.io/blog/upgrading-frontend-dependencies-with-confidence-using-visual-regression-testing

This might be something we want to add.

### PR DESCRIPTION
**Pull request by devilkiller-ag**
# Summary of Changes

Implemented CI Workflow for visual regression testing using Argos and Playwright.

## Related Issue

Closes #99

## Checklist

- [x] I have read and followed the [project's contribution guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md), including code style and commit message conventions.
- [x] My code is well-documented, and I've updated relevant documentation.
- [x] I have added or updated test cases to ensure the code's functionality.
- [x] I have tested these changes on my local environment.
- [x] All tests pass, and there are no new linting errors.
- [x] I have reviewed and proofread my code and the changes.
- [x] The branch is up-to-date with the base branch.

## Reviewer(s)
@hexsecs

### CODE REVIEW

**Comment by hexsecs** [comment]
@devilkiller-ag  - I think we might be missing something here. My understanding is that there is github workflow created for this also.
See...
https://docusaurus.io/blog/upgrading-frontend-dependencies-with-confidence-using-visual-regression-testing
https://github.com/slorber/docusaurus-argos-example

**Comment by devilkiller-ag** [comment]
Hi @hexsecs, Yeah I noticed that we missed connecting this repo with Argos (https://argos-ci.com/docs/github). I think this has to be done by project owner.

**Comment by hexsecs** [comment]
@devilkiller-ag to get this working we need a workflow added to the repository also. See the example here...
https://github.com/slorber/docusaurus-argos-example

**Comment by devilkiller-ag** [comment]
> @devilkiller-ag to get this working we need a workflow added to the repository also. See the example here...
> https://github.com/slorber/docusaurus-argos-example

Okay Sure I will check it out

**Comment by devilkiller-ag** [comment]
@hexsecs I have added the workflow now. Kindly check it out!

**Review by hexsecs — CHANGES_REQUESTED** [review]
We finally merged the docusaurus code into the main branch recently. Currently your actions are set up to act on main. This is fine and actually what we want, however the pull request is against the `uptane_docusaurus` branch. Can you fix to reflect the `main` branch? If it is easier you can cancel the pull and resubmit against `main`.

**Comment by Abhijay007** [comment]
I think you can change the branch from directly from github, there is
option to change branch at the top of PR, it will then point to the `main`
branch then you might not need to create a new PR and just might need to
change branch in actions.

**Review by hexsecs — APPROVED** [review]
I was able to change the merge into branch myself. Looks good thanks!

**Comment by devilkiller-ag** [comment]
Thanks @hexsecs 😊

**Pull request merged**
