### PR TITLE
Add Deployment Best Practices 1.1.0 for 1.1.0 release

### PR DESCRIPTION
**Pull request by mnm678**
This pr add the html and pdf versions of the Deployment Best Practices, and adds them to the menu.

Signed-off-by: Marina Moore <mnm678@gmail.com>

### CODE REVIEW

**Review by pattivacek — COMMENTED** [review]
Cool, looks great!

I have a few minor nits:
1. papers/assets/images/.DS_Store should not be included, that's some filesystem metadata.
2. The "Uptane is a Joint Development Foundation project" bit seems out of place after the changelog. Should that be part of the intro? Not a big deal in any case, and if it's not easy to move it right now, don't worry about it.
3. Is it also necessary to add all the png files? I thought they were already in the deployment repo, so it's slightly annoying to have them here as well. Not a big deal either, though. Is this an issue of which repo the pdf gets constructed from?

**Comment by mnm678** [comment]
Thanks for the review! 

>     1. papers/assets/images/.DS_Store should not be included, that's some filesystem metadata.
> 
>     2. The "Uptane is a Joint Development Foundation project" bit seems out of place after the changelog. Should that be part of the intro? Not a big deal in any case, and if it's not easy to move it right now, don't worry about it.

These first 2 should be fixed after the force push.

>     3. Is it also necessary to add all the png files? I thought they were already in the deployment repo, so it's slightly annoying to have them here as well. Not a big deal either, though. Is this an issue of which repo the pdf gets constructed from?

These are for the html version of the best practices. I couldn't figure out a way to reference them from the deployment repo.

**Review by jhdalek55 — COMMENTED** [review]
In addition to putting the links to the Best Practices in the master list, you need to change the text on the "Standards Reference Center." Right now it says "See relevant pages under the Deployment Best Practices tab."

**Review by jhdalek55 — APPROVED** [review]
LGTM

**Comment by jhdalek55** [comment]
If there are no objections, I will merge this today. @pattivacek, were your concerns resolved?

**Review by pattivacek — APPROVED** [review]
Yep, LGTM!

**Comment by jhdalek55** [comment]
I've re-done the changelog, so that will need to be replaced. If we can get an OK on PR #93, we can get this posted. I want this up as soon as we can, but I want to make sure the correct copy is in place.

**Comment by jhdalek55** [comment]
@pattivacek @tkfu @mnm678  I'd like to get this posted, but before I merged it, I wanted to see if this conflicts with the automatic build for Deployment pages that was proposed by @tkfu. As I recalled, there were several missing pieces from the PDF generated by Jon so if we use that document we need to add those components. If we're not ready to do this automatic generation can I merge this PR so we get the Deployment document posted? We sent a press release out nearly six weeks ago that it exists, so its sort of urgent that we get something posted.

**Comment by mnm678** [comment]
I'd say we can merge this for the current release to get it done, then add the final touches to the PDF generation before the next release.

**Comment by pattivacek** [comment]
> I'd say we can merge this for the current release to get it done, then add the final touches to the PDF generation before the next release.

Yep, agreed. I didn't realize we hadn't already merged this!

**Comment by jhdalek55** [comment]
Ok. Merging now.

**Comment by jhdalek55** [comment]
Ok. The documents are up, but this has the old changelog...the one that is not properly formatted. The changelog page doesn't show up on the website pages, but the correct version is on the Deployment repo. I was going to go in and edit the page on the website, but it doesn't exist there. How do we fix this?

**Comment by mnm678** [comment]
This is the downside to the manual method here, I'll get that fixed and open a new pr.

**Pull request merged**
