### PR TITLE
LD filling deployment

### PR DESCRIPTION
**Pull request by jhdalek55**
Ok. I completed transferring two of the sections to the template files on the "feat/deployment" branch.  I planned to wait till I was finished with everything before do a pull request. But, I went ahead and opened this, because I  an not sure where this  commit went.  The deployment materials are not on the master branch yet, so this commit can not be merged to master. I need to get this over to the branch established by Jon for holding the deployment copy.

If this commit is just sitting on my local repository can I guess a merge would be OK for now and I'll just continue to add to this PR. If its going to master, please don't commit.

Lois

### CODE REVIEW

**Comment by patrickvacek** [comment]
@jhdalek55 What happened here? I think what you wanted to do was make this PR against the https://github.com/uptane/uptane.github.io/tree/feat/deployment-guidelines branch. Then maybe it would look more correct?

**Comment by jhdalek55** [comment]
I have mentioned several times that my github skills are somewhat 
limited. I was working remotely and planned to keep everything on my 
branch until I was done and then I was going to open a pull request. I 
was working with a version of Jon's deployment branch on my computer. 
When I thought I was committing to my branch, it seemed to commit to the 
master. So I removed the pull request. The point is I was not ready to 
share this with the group. 


If there are formatting issues, I'm happy to discuss this moving 
forward. Or if we can come up with some kind of work around, even 
better.


Lois

On Tue, Mar 26, 2019 at 03:56 AM, Patrick Vacek wrote:

@jhdalek55 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jhdalek55&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=pT7Wk1U8tOGBt_dC_56Dokwkphat3NDNB50hKrAoDz8&s=0z2RxnpGxKzyUU9wTPELhyqyvoAqA9P9Twohl8J7B1o&e=> 
What happened here? I think what you wanted to do was make this PR 
against the 
https://github.com/uptane/uptane.github.io/tree/feat/deployment-guidelines 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane.github.io_tree_feat_deployment-2Dguidelines&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=pT7Wk1U8tOGBt_dC_56Dokwkphat3NDNB50hKrAoDz8&s=0mjovUmzsk0lHvhfREHEHyf9nJ0lzVRc0w7stZkvDAQ&e=> 
branch. Then maybe it would look more correct?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane.github.io_pull_9-23issuecomment-2D476513333&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=pT7Wk1U8tOGBt_dC_56Dokwkphat3NDNB50hKrAoDz8&s=L68gZYJILOTKbCNGqeXzUO_wejBeQeF47Ht4fR8n8nQ&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qX0dKshnToDSbhr3DrIz030XAkI8Dks5vadK6gaJpZM4cHcYJ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=pT7Wk1U8tOGBt_dC_56Dokwkphat3NDNB50hKrAoDz8&s=6rgogb7RZ7bQIa5iAT6LMwEZdf_NGiTr-2Be6-zVEFA&e=> 
.

**Comment by patrickvacek** [comment]
> I have mentioned several times that my github skills are somewhat limited. I was working remotely and planned to keep everything on my branch until I was done and then I was going to open a pull request. I was working with a version of Jon's deployment branch on my computer. When I thought I was committing to my branch, it seemed to commit to the master. So I removed the pull request. The point is I was not ready to share this with the group.

Oh, sorry! Didn't mean to give you extra trouble. Let me know if something comes up that you need help with.

**Comment by jhdalek55** [comment]
I hope that my response did not come across as too defensive, as that 
was certainly not my intention. I'm afraid this project is just 
stretching my github muscles further than I've ever needed them to and, 
though this is generally a good thing--I would like to be more 
proficient than I currently am--but it can berather stressful as well.


I was quite serious in saying I would welcome suggestions for the best 
way to do this. Its a strictly mechanical task, and that's why I don't 
want to waste anyone else's time with having to do it. I had someone 
integrate Jon's branch into my clone of the web site repo and am working 
remotely. I admit I'm a bit unsure of how to export this to the branch. 


Was the formatting of the text you saw weird? Was there odd spacing 
issues? I'm literally just cutting and pasting this in, as I have worked 
this way before in Markdown, but unlike previous projects, I don't have 
a way to check how it looks. So, before I go further, please tell me 
what you saw that was amiss.


I'm squeezing this transfer work in-between a few other projects so I 
probably won't get back to it until later in the week. If you or Jon can 
suggest a better way to do this (i.e maybe if I set up a separate branch 
on the repo and then merge with his branch that way?). 


Lois

On Tue, Mar 26, 2019 at 10:58 AM, Patrick Vacek wrote:


I have mentioned several times that my github skills are somewhat 
limited. I was working remotely and planned to keep everything on my 
branch until I was done and then I was going to open a pull request. I 
was working with a version of Jon's deployment branch on my computer. 
When I thought I was committing to my branch, it seemed to commit to the 
master. So I removed the pull request. The point is I was not ready to 
share this with the group.


Oh, sorry! Didn't mean to give you extra trouble. Let me know if 
something comes up that you need help with.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane.github.io_pull_9-23issuecomment-2D476687455&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=o7X-U_bp0cZnDXBHPCPTV23wBaMaLUktZRD3v2LHU4w&s=IQPH6Rddx0915uH-WBI2Tff3RGjoKhqRNH40lcHKIxU&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qX3Jyol2ssL7yYKKN6LkGDiomARv2ks5vajWSgaJpZM4cHcYJ&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=o7X-U_bp0cZnDXBHPCPTV23wBaMaLUktZRD3v2LHU4w&s=aPkUa_31rBuagzuuIfogDnD0htzCH_-iDJuMHu3v3ms&e=> 
.

**Comment by patrickvacek** [comment]
> I hope that my response did not come across as too defensive, as that was certainly not my intention.

No worries at all, Lois! I was just checking that something hadn't gone awry.

> Was the formatting of the text you saw weird? Was there odd spacing issues?

I took a quick glance at the [commit](https://github.com/uptane/uptane.github.io/pull/9/commits/fe47b2d2309c63f3e07bd96e4b16a2d57749fcbd) (as well as [Github's default rendering](https://github.com/jhdalek55/uptane.github.io/blob/fe47b2d2309c63f3e07bd96e4b16a2d57749fcbd/deployment/customizations.md)) and it looked fine to me so far with one exception: there are a few places with unnecessary line breaks. (See for example [here](https://github.com/uptane/uptane.github.io/pull/9/commits/fe47b2d2309c63f3e07bd96e4b16a2d57749fcbd#diff-3cff0480d7057fb0633df70c0a00971cR16).) Not a big problem, though, and that's easy enough for me to fix if it isn't easy for you.

> If you or Jon can suggest a better way to do this (i.e maybe if I set up a separate branch on the repo and then merge with his branch that way?).

That seems to me to be exactly what Jon had in mind, and I believe that branch already exists: [feat/deployment-guidelines](https://github.com/uptane/uptane.github.io/tree/feat/deployment-guidelines). Then, when you are ready, you can make a pull request that looks something like [this](https://github.com/uptane/uptane.github.io/compare/feat/deployment-guidelines...jhdalek55:LDcontent-filling-deployment): i.e., request to merge your branch into that feature branch.

(@tkfu it looks like that feature branch needs rebasing. Can you take care of that? I don't have write access here.)

**Pull request closed without merging**
