### PR TITLE
Jhdalek55 patch 1

### PR DESCRIPTION
**Pull request by jhdalek55**
This is the pull request containing the cover page .

### CODE REVIEW

**Comment by jhdalek55** [comment]
@trishankatdatadog. Please make sure this all makes sense now.

**Comment by trishankatdatadog** [comment]
@jhdalek55 LGTM! So the current thinking is that we don't want to point to the "unstable" version of the Uptane Standard anywhere, right?

**Comment by jhdalek55** [comment]
Not sure what you mean by "unstable?" The HTML?

**Comment by jhdalek55** [comment]
@JustinCappos OK Trishank approved, so shall I merge? Or did you want to take one more look?

**Comment by trishankatdatadog** [comment]
@jhdalek55 yes, by "unstable," i mean the non-versioned HTML, the one that is continuously evolving

**Comment by jhdalek55** [comment]
We do have a PDF link. At the bottom of the pull down where all the links
will be posted.

**Comment by trishankatdatadog** [comment]
@jhdalek55 I understand, but the PDF points to IEEE-ISTO version, you see? I'm talking about this: https://uptane.github.io/uptane-standard/uptane-standard.html

**Comment by jhdalek55** [comment]
Let me check the link.

Lois

**Comment by jhdalek55** [comment]
Ok. I think I understand the question. It points to the IEEE/ISTO now
because that is the current version. When we publish V.1.0.1. , the link
will point to point to the new current version and the IEEE/ISTO link will
go to the "reference"  page. No, I think there is some value in all things
pointing towards a versioned document. The versioning and the imprimatur of
the releasing organization offers credibility whereas an unstable version
doesn't offer either of these.

If there is a compelling reason to point to such a version, it would be
easy to find a place to offer that link.

Lois

**Pull request merged**
