### PR TITLE
Link updates for 2.1.0 release

### PR DESCRIPTION
**Pull request by tkfu**

### CODE REVIEW

**Review by pattivacek — COMMENTED** [review]
Should the changelog links link to the specific subsections? Or am I being too nitpicky?

**Comment by tkfu** [comment]
No, you're right: that's not too nitpicky. Gimme a sec and I'll change it. The changelog doesn't actually have anchor links for the different releases, but it should be possible with the generated heading ids. BRB.

**Review by pattivacek — COMMENTED** [review]
Thanks!

**Comment by pattivacek** [comment]
I approve, but I don't have the rights to formally do so.

**Pull request merged**
