### PR TITLE
removing time server from design explanation

### PR DESCRIPTION
**Pull request by jhdalek55**

### CODE REVIEW

**Comment by jhdalek55** [comment]
There was a glitch on my last PR to remove the timeserver from the Design page on the website. I decided to delete that document and do it over to make sure the image was on the same PR. This appears to have resolved things. Please review so we can merge as quickly as possible.

**Comment by lukpueh** [comment]
There are some artifacts in the new image (see red circles)

Screen Shot 2022-04-01 at 09 40 55


Do we have the original editable document somewhere, so that we don't have to draw over the png file? Also, I saw that there are several versions of this file in the repo now (`Uptane_process 324.png`, `Uptane_process.png`, `Uptane_process_324.png`, `Uptane_process_331.png`), I think you can rename the final version to `Uptane_process.png` and remove the other. Let me know if you need help.

**Comment by jhdalek55** [comment]
Hey, Lukas. Thanks for following up on this.

I don't know where the original of this document came from. I placed it on this site when we built the website after copying it from the design Google doc. I don't have any programs to edit graphics. Hence, all I could do is try to patch the png I had. 

It's rather important that we NOT have a document showing the Time Server and the movement of tokens on the web site as this option has been removed from the Standard in V.2.0.0. I'm aware that this document had to be recreated and that it looked kind of messy. But in the interest of accuracy I did what I could as a stop gap.

I  had some issues trying to remove the previous versions of the file. The correct one now is _331.png.

If you can figure out a way to edit the file, great.

**Comment by lukpueh** [comment]
Just pushed an update. I think it's better now. Let me know what you think.

**Comment by jhdalek55** [comment]
Can we get a review on this so we can merge it? This contains references top the time server that need to be removed ASAP.

**Comment by lukpueh** [comment]
Lois, if you take another look at the [document as it looks now](https://github.com/uptane/uptane.github.io/blob/64863d887576866817dc9b466cd036ab5f87837d/design.md), I think we can just go ahead and merge. Or maybe @mnm678 wants to green-light this?

**Comment by jhdalek55** [comment]
I think it looks fine, but I need one more person to review it. @mnm678 can do this.

**Review by mnm678 — APPROVED** [review]
Looks great!

**Pull request merged**
