### PR TITLE
Adding conference announcement to home page

### PR DESCRIPTION
**Pull request by jhdalek55**
This is the only way I could figure out to post something about the meeting on the home page. I have created a PDF of the "save the date" flyer and stored it with the publications on this site, which I will add to this pull request. If someone can think of a better way to spotlight the workshop on this page, let me know.

### CODE REVIEW

**Comment by jhdalek55** [comment]
@JustinCappos @tkfu @mnm678  or anyone else. It's important we get this listing up on our home page. If you can suggest a better way, please do so. Otherwise, review, approve, etc. so we can move this admittedly jury-rigged solution forward.

**Comment by jhdalek55** [comment]
@pattivacek --I agree this is not a great solution. But, there is simply too much text to add all the conference information directly to the home page. Other suggestions?

**Comment by jhdalek55** [comment]
This PR was approved at the 9/27 For this one time, we'll use the PDF as a solution. I will, however, wait to post until we have the complete text for the workshop, as opposed to the initial text.

**Comment by pattivacek** [comment]
Oh, I wish we'd just removed the commit with the pdf. As it is now, we've added a binary to the repo that will now be there forever.

**Comment by jhdalek55** [comment]
@pattivacek I am a bit confused about the PDF issue. We already have links to PDFs for our papers, whitepapers, etc.  Why is this one problematic?

**Comment by pattivacek** [comment]
Short version: it's probably fine. It's really not that big a deal for our use case. These PDFs are fairly small and normally don't change.

Long version: historically, git was not built for storing binary files. It doesn't have good tools for diffing binary files, meaning that if you add a binary and then make a tiny change to it, it has to store the entirety of both copies. This can add up and cause a repo to end up requiring quite a bit of disk space and memory to use. I've seen a degenerate case where a repo ended up in the gigabytes as a result of this.

That said, git does have features for trying to work around this, most notably git-lfs (Large File Storage). I don't think we're using that here, but we could. It's basically a more efficient way of dealing with this problem.

And for a repo like this that is meant to contain all the source for a website, there aren't a lot of good choices. You often need to add binary files. However, it's worth trying to only add things that are strictly necessary and to try to choose filetypes and compression mechanisms to keep these objects as small as possible.

In this case, I complained simply because a file was added in the PR and then removed in a later commit in the same PR. It would've been better to just remove or edit the commit that added the file in the first place, such that the git history on master would not have to ever know about the file. As it is, that file is now embedded in the git history, and everyone who clones this repo will get a copy of that file, despite that it isn't in the latest head. (Well, not necessarily, but that's another complicated story.) But like I said, it's not a big file, and the repo isn't huge, so it's not a big deal.

**Comment by jhdalek55** [comment]
I appreciate the clarification, @pattivacek. In the future, we'll try to come up with a more elegant solution.

**Pull request merged**
