### PR TITLE
Update package.json

### LINKED ISSUE #113: [Bug Report] - Fix security vulnerabilities flagged by dependabot
### Describe the bug.

Dependabot found two vulnerabilities that cannot automatically be fixed due to pinned versions.
image

They look to be fixed in v3.x of docusaurus. The patch to resolve is listed here...
https://github.com/facebook/docusaurus/issues/8277

While these probably won't cause any issues. It's easy enough to fix.

### Describe the steps to reproduce the behavior.

_No response_

### Expected behavior.

_No response_

### Screenshots.

_No response_

### Operating environment

all

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hexsecs**
# Summary of Changes

Created dependency resolutions to fix the following dependabot alerts.
https://github.com/uptane/uptane.github.io/security/dependabot/1
https://github.com/uptane/uptane.github.io/security/dependabot/2

## Related Issue

Closes #113 

## Checklist

- [x] I have read and followed the [project's contribution guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md), including code style and commit message conventions.
- [x] My code is well-documented, and I've updated relevant documentation.
- [x] I have added or updated test cases to ensure the code's functionality.
- [x] I have tested these changes on my local environment.
- [x] All tests pass, and there are no new linting errors.
- [x] I have reviewed and proofread my code and the changes.
- [x] The branch is up-to-date with the base branch.

## Screenshots (if applicable)

Attach any screenshots or images related to the changes.

## Additional Context

Add any additional context or information that might be helpful for reviewers.

## Reviewer(s)

@mention any specific reviewers or tag relevant team members.

### CODE REVIEW

**Comment by hexsecs** [comment]
@Abhijay007 @JustinCappos I created a pull request to fix those pesky dependency vulnerabilities from dependabot. Everything looks to be working fine after following the suggestion of manually updating the trim and got packages.

**Comment by hexsecs** [comment]
@Abhijay007 according this this it is best practice to version your yarn.lock.

https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for

**Comment by Abhijay007** [comment]
Ya according to this It's LGTM

**Comment by hexsecs** [comment]
Here is the docu from the official yarn site about it...

# Check into source control
All yarn.lock files should be checked into source control (e.g. git or mercurial). This allows Yarn to install the same exact dependency tree across all machines, whether it be your coworker’s laptop or a CI server.

Framework and library authors should also check yarn.lock into source control. Don’t worry about publishing the yarn.lock file as it won’t have any effect on users of the library.

See https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/.

**Comment by Abhijay007** [comment]
Ya this makes much sense now, thanks for sharing we can keep the yarn.lock
files

**Pull request closed without merging**
